In [51]:
'hello world'

'hello world'

In [52]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0


In [53]:
import torch
print("MPS available:", torch.backends.mps.is_available())
device = "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)

MPS available: True
Using device: mps


# Introduction to tensors

## creating tensor

In [54]:
scaler = torch.tensor(8)
scaler

tensor(8)

In [55]:
scaler.ndim

0

In [56]:
scaler.item()

8

In [57]:
vector = torch.tensor([8,3])
vector.ndim, vector.shape

(1, torch.Size([2]))

In [58]:
MATRIX = torch.tensor([[5,4],
                       [0,4]])
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [59]:
TENSOR = torch.tensor([[[[1,3,4]]]])

In [60]:
TENSOR.ndim

4

In [61]:
TENSOR.shape

torch.Size([1, 1, 1, 3])

### Random tensors

In [62]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7664, 0.1214, 0.7954, 0.4352],
        [0.5170, 0.5564, 0.2906, 0.2689],
        [0.1791, 0.8133, 0.9065, 0.6764]])

In [63]:
random_tensor = torch.rand(2,2,2,1,2)
random_tensor

tensor([[[[[0.1902, 0.6354]],

          [[0.5893, 0.2205]]],


         [[[0.1644, 0.6214]],

          [[0.9608, 0.5619]]]],



        [[[[0.9601, 0.5645]],

          [[0.2417, 0.2759]]],


         [[[0.5777, 0.8931]],

          [[0.5022, 0.3109]]]]])

In [64]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [65]:
tensor * tensor

tensor([1, 4, 9])

In [66]:
torch.matmul(tensor,tensor)

tensor(14)

In [67]:
tensor @ tensor

tensor(14)

In [68]:
tensor.dtype

torch.int64

In [69]:
torch.mean(tensor.type(torch.float32))

tensor(2.)

In [70]:
tensor = tensor.type(torch.float32)

In [71]:
tensor

tensor([1., 2., 3.])

In [72]:
tensor.dtype

torch.float32

In [73]:
tensor.sum()

tensor(6.)

In [74]:
tensor.min()

tensor(1.)

In [75]:
tensor.max()

tensor(3.)

# reshape, vew, stack, squeeze, unsqueeze, permute

In [77]:
import torch
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [78]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [79]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=1) # dim=0 by default
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [85]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape {x_reshaped.shape}")

X_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {X_squeezed}")
print(f"New shape: {X_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [86]:
X_squeezed_stack = x_stacked.squeeze()

In [88]:
x_stacked.shape, X_squeezed_stack.shape

(torch.Size([7, 4]), torch.Size([7, 4]))

In [89]:
x_stacked, X_squeezed_stack

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.]]))

In [93]:
X_original = torch.rand(size=(224,224,3))
x_permuted = X_original.permute(2,0,1)
X_original.shape, x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# numpy and tensor

In [95]:
# Numpy array to tensor
import torch
import numpy
array = np.arange(1.0, 11.0)
tensor = torch.from_numpy(array)
array, tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [96]:
# Tensor to Numpy array
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In [111]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

display(random_tensor_A, random_tensor_B)
print(f"Does Tensor A equal Tensor B? (anywhere) {random_tensor_A == random_tensor_B}")

tensor([[0.2726, 0.3186, 0.6571, 0.1543],
        [0.5663, 0.5660, 0.8744, 0.9515],
        [0.4903, 0.9675, 0.0119, 0.6609]])

tensor([[0.1862, 0.0885, 0.7273, 0.6768],
        [0.0996, 0.9523, 0.9381, 0.9448],
        [0.4550, 0.2035, 0.3499, 0.1320]])

Does Tensor A equal Tensor B? (anywhere) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [116]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# With out this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

display(random_tensor_C, random_tensor_D)
random_tensor_C == random_tensor_D

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running Tensor on GPU

### for Nvidia gpu

In [120]:
import torch
torch.cuda.is_available()

False

In [121]:
device = "cude" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [122]:
torch.cuda.device_count()

0

### For Apple Silicon

In [123]:
import torch
torch.backends.mps.is_available()

True

In [125]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

### step 1: for both nvidia and mac

In [126]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'

device

'mps'

## Step 2: putting tensors (and models on the gpu)

In [127]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [128]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

### moving tensors back to cpu

In [131]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu, tensor_on_cpu.device

(array([1, 2, 3]), 'cpu')